Make the mod server friendly
Low-Drag-MC/LDLib-MultiLoader pull request #28
Opened 2024-07-07 14:21 UTC by JustRed23

The mod was not serverside friendly, crashing on boot, I fixed that.

Some things to note:
- if you do not have a @SubscribeEvent in your class, do not register the class as it will error
- @OnlyIn(Dist.CLIENT) will actually remove the method that is annotated with that from the mod on the server dist, making those methods completely unknown to Java, causing a NoSuchMethodError

2024-07-07 14:22 UTC, JustRed23 commented
Fixes #27 & https://github.com/GregTechCEu/GregTech-Modern/issues/1553

2024-07-08 04:45 UTC, JustRed23 commented
Apparently the registries were getting mixed between client and serverside as well, as they were not correctly set to null, creating a decoderexception on an attempted login

2024-07-08 04:45 UTC, JustRed23 commented
Here's an example of what that looked like: https://mclo.gs/FiUYHLF

2024-07-08 08:21 UTC, Ashley123477 commented
Will verify by testing new commits later on today.

2024-07-08 15:40 UTC, Ashley123477 commented
After testing this now works and allows you to use Latest GT Modern Versions for 1.21 with servers.

2024-07-08 16:06 UTC, screret requested changes

2024-07-08 16:06 UTC, screret commented on src/main/java/com/lowdragmc/lowdraglib/LDLib.java
> +            return !Minecraft.getInstance().isSameThread();
isRemote is the same as `Level#isClientSide`, so this is wrong.

2024-07-08 16:12 UTC, screret commented
eh whatever, I'll just fix it myself.

2024-07-08 16:12 UTC, merged

2024-07-08 16:14 UTC, JustRed23 commented
> eh whatever, I'll just fix it myself.

In that case, change Platform.getFrozenRegistry to use !isRemote instead

2024-07-08 16:39 UTC, screret commented
I'm fairly certain that it should be using isRemote == true to check for the client side?

2024-07-08 16:45 UTC, Ashley123477 commented
As of now with those PR commits, it allows the server to launch and the Client to connect, having an issue, crashes out once opening inventory
[crash-2024-07-08_17.43.10-client.txt
[latest.log](https://github.com/user-attachments/files/16132161/latest.log)
](https://github.com/user-attachments/files/16132160/crash-2024-07-08_17.43.10-client.txt)

2024-07-08 17:01 UTC, screret commented
yes yes fixing that

2024-07-08 17:03 UTC, Ashley123477 commented
> yes yes fixing that

Throw the jar over once built and ill test it